services:
  chaohuyun:
    image: ghcr.io/jlfba/choahuyun:latest
    container_name: chaohuyun
    restart: unless-stopped
    ports:
      - "8066:8066"
    volumes:
      - ./config.json:/app/config.json:ro
      - ./output:/app/output
    environment:
      - TZ=Asia/Shanghai
